# Configuration A (Baseline)
# Primary thesis validation scenario
# Validated against: Bor+ MSWiM 2016, Magrin+ ICC 2017
#
# Purpose: Standard Byzantine consensus scenario for LPWAN networks
# Represents: Moderate-scale deployment (100 nodes, 10% Byzantine, G≈1.0)
# Parameter values: ε, σ chosen as representative for distributed sensing

name: "Configuration A (Baseline)"
description: "N=100, f=10%, SF9 - Primary validation scenario"

network:
  spreading_factor: 9
  bandwidth_hz: 125000
  tx_power_dbm: 14
  duty_cycle: 0.01
  num_nodes: 100
  deployment_area_m: 1000
  payload_bytes: 51

consensus:
  epsilon: 1.0
  initial_ci_width: 5.0
  noise_std_dev: 0.5
  lambda_min: 0.08
  lambda_max: 0.18
  iou_threshold: 0.20
  consistency_vote_threshold: 0.50
  trim_min: 2
  trim_max_fraction: 0.20
  estimator: "geometric_median"
  change_detection: "cusum"

adversarial:
  byzantine_fraction: 0.10
  attack_mix:
    MIMIC: 0.50
    COLLIDER: 0.20
    SPIKE: 0.20
    DRIFT: 0.10
  mimic_bias: 0.5
  spike_magnitude: 20.0
  drift_rate: 0.1

ground_truth:
  baseline_value: 25.0
  changes:
    - time: 0
      value: 25.0
    - time: 1200
      value: 28.0  # Step change at t=1200s (tests re-stabilization)
    - time: 1800
      value: 25.0  # Return to baseline at t=1800s

seeds: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19]
max_rounds: 5000

