# Sensitivity Sweep Template
# For PhD defense: "Algorithm works across parameter ranges"

name: "Sensitivity Sweep"
description: "Template for parameter sensitivity analysis"

network:
  spreading_factor: 9  # SWEEP: [7, 9, 12]
  bandwidth_hz: 125000
  tx_power_dbm: 14
  duty_cycle: 0.01  # SWEEP: [0.005, 0.01, 0.02]
  num_nodes: 100  # SWEEP: [50, 100, 200]
  deployment_area_m: 1000
  payload_bytes: 51

consensus:
  epsilon: 1.0
  initial_ci_width: 5.0
  noise_std_dev: 0.5
  lambda_min: 0.08
  lambda_max: 0.18
  iou_threshold: 0.20  # SWEEP: [0.10, 0.15, 0.20, 0.25]
  consistency_vote_threshold: 0.50
  trim_min: 2
  trim_max_fraction: 0.20
  estimator: "geometric_median"
  change_detection: "cusum"

adversarial:
  byzantine_fraction: 0.10  # SWEEP: [0.0, 0.05, 0.10, 0.15, 0.20]
  attack_mix:
    MIMIC: 0.50
    COLLIDER: 0.20
    SPIKE: 0.20
    DRIFT: 0.10
  mimic_bias: 0.5
  spike_magnitude: 20.0
  drift_rate: 0.1

ground_truth:
  baseline_value: 25.0
  changes:
    - time: 0
      value: 25.0

seeds: [0, 1, 2, 3, 4]  # Fewer seeds for sweeps
max_rounds: 2000

